# Credits

This is heavily based on https://github.com/pytorch/tutorials

### **Questions**

**Question 4**
Answer: D - True

**Question 7** 
Answer: C - False (A): The dimension for the softmax is dim=1, which is not true for 3 classes.

**Question 9** 
Answer: C - False (D): The output from y[:,0] or y[:,1] can be negative, meaning the logarithmic value becomes invalid, and we therefore needs to take the exponential of it.

### **Question 9.4**

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[2.1044e-26, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7084, 0.4445, 0.5769],
        [0.7579, 0.3930, 0.2859],
        [0.5731, 0.5816, 0.5431],
        [0.2933, 0.5540, 0.5387],
        [0.2376, 0.1056, 0.4444]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.7084, 0.4445, 0.5769],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2933, 0.5540, 0.5387],
        [0.2376, 0.1056, 0.4444]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [20]:
print("Task 1: Make a tensor of size (2,17)")
task1 = torch.Tensor(2, 17)
print(task1)

print("\nTask 2: Make a torch.FloatTensor of size (3, 1)")
task2 = torch.FloatTensor(3, 1)
print(task2)

print("\nTask 3: Make a torch.LongTensor of size (5, 2, 1)")
task3 = torch.LongTensor(5, 2, 1)
task3.fill_(7)
print(task3)

print("\nTask 4: Make a torch.ByteTensor of size (5,)")
task4 = torch.ByteTensor(5,).zero_()
task4[1:4] = 1
print(task4)

Task 1: Make a tensor of size (2,17)
tensor([[7.1856e+22, 1.8609e+34, 1.8179e+31, 1.8524e+28, 1.5766e-19, 1.4610e-19,
         7.3159e+34, 1.6634e+22, 1.7937e-43, 0.0000e+00, 1.7937e-43, 0.0000e+00,
         2.1650e-26, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

Task 2: Make a torch.FloatTensor of size (3, 1)
tensor([[2.1691e-22],
        [0.0000e+00],
        [0.0000e+00]])

Task 3: Make a torch.LongTensor of size (5, 2, 1)
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

Task 4: Make a torch.ByteTensor of size (5,)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [21]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2507, 1.0596, 0.7622],
        [2.8925, 2.9492, 2.5188],
        [2.2630, 2.4314, 2.4071],
        [0.3520, 1.1444, 0.7198],
        [0.4582, 0.7743, 1.1727]])


### 2.2 Addition: syntax 2

In [22]:
print(torch.add(x, y))

tensor([[1.2507, 1.0596, 0.7622],
        [2.8925, 2.9492, 2.5188],
        [2.2630, 2.4314, 2.4071],
        [0.3520, 1.1444, 0.7198],
        [0.4582, 0.7743, 1.1727]])


### 2.3 Addition: giving an output tensor

In [23]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2507, 1.0596, 0.7622],
        [2.8925, 2.9492, 2.5188],
        [2.2630, 2.4314, 2.4071],
        [0.3520, 1.1444, 0.7198],
        [0.4582, 0.7743, 1.1727]])


### 2.4 Addition: in-place

adds `x` to `y`

In [24]:
y.add_(x)
print(y)

tensor([[1.2507, 1.0596, 0.7622],
        [2.8925, 2.9492, 2.5188],
        [2.2630, 2.4314, 2.4071],
        [0.3520, 1.1444, 0.7198],
        [0.4582, 0.7743, 1.1727]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [25]:
print(x[:, 1])

tensor([0.4445, 2.0000, 2.0000, 0.5540, 0.1056])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [30]:
x = torch.randn(4, 4)
y = torch.randn(4, 4)



print("Multiplication of two tensors")
result1 = torch.Tensor.mul(x, y)
print(result1)

result2 = x*y
print(result2)

print("Division of two tensors")
result3 = torch.Tensor.div(x, y)
print(result3)


print("Matrix multiplication of two tensors")
x = torch.randn(2, 4)
y = torch.randn(4, 2)
result4 = torch.Tensor.mm(x, y)
print(result4)

Multiplication of two tensors
tensor([[-1.3630, -0.1523,  0.0975,  0.0650],
        [ 0.3541,  0.0562, -0.0558,  1.1494],
        [ 0.0093, -0.0984,  1.1842, -1.0243],
        [ 3.2529, -0.0308,  0.0428,  1.6124]])
tensor([[-1.3630, -0.1523,  0.0975,  0.0650],
        [ 0.3541,  0.0562, -0.0558,  1.1494],
        [ 0.0093, -0.0984,  1.1842, -1.0243],
        [ 3.2529, -0.0308,  0.0428,  1.6124]])
Division of two tensors
tensor([[-1.2448, -0.0598,  0.9422,  0.5593],
        [ 0.2709,  1.1649, -8.7206,  1.3857],
        [ 0.0348, -5.4363,  2.7260, -0.5520],
        [ 1.6634, -0.1446,  0.2409,  1.3016]])
Matrix multiplication of two tensors
tensor([[ 0.1536,  0.7651],
        [-0.9059, -0.3127]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [33]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [34]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [35]:
print("Task 1: Create a tensor of size (5,2) containing ones")
tensor1 = torch.ones(5,2)
print(tensor1)

print("Task 2: Now convert it to a NumPy array")
tensor1_np = tensor1.numpy()
print(tensor1_np)

print("Task 3: Convert it back to a torch tensor")
tensor1_back = torch.from_numpy(tensor1_np)
print(tensor1_back)


Task 1: Create a tensor of size (5,2) containing ones
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
Task 2: Now convert it to a NumPy array
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Task 3: Convert it back to a torch tensor
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [36]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
